POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "test3",
    "author": "Medicine man",
    "url": "a place",
    "likes": "-2",
    "userId": "5f00c71aa884342afc18d89b"
}